---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s-hostpath-provisioner
  labels:
    app.kubernetes.io/name: k8s-hostpath-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-hostpath-provisioner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-hostpath-provisioner
    spec:
      serviceAccount: k8s-hostpath-provisioner-sa
      restartPolicy: Always
      containers:
        - name: hostpath-provisioner
          image: 'ayesolutions/k8s-hostpath-provisioner'
          imagePullPolicy: Always
          env:
            - name: PROVISIONER_PATH
              value: /container/data/k8s
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /container/data/k8s
      volumes:
        - name: data
          hostPath:
            path: /host/data/k8s
