---
apiVersion: v1
kind: Pod
metadata:
  name: test-pvc
spec:
  containers:
  - image: busybox
    name: test-container
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: claim1
