---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-hostpath-provisioner
  resources:
    requests:
      storage: 1Gi